server:
  port: 8082
spring:
  application:
    name: Ribbon-Consumer
##providers这个是自己命名的，ribbon,listOfServer这两个是规定的
#providers:
#  ribbon:
#    listOfServers: localhost:8080,localhost:8081

eureka:
#客户端
  client:
#注册中心地址
    service-url:
      defaultZone: http://10.36.0.4:30382/eureka/
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    hostname: ${spring.cloud.client.ip-address}